version: "3.6"

services:

  database:
    image: mongo:4.0.8
    command: mongod --port 27018
    restart: unless-stopped
    env_file:
      - ./docker/config/database.env
    volumes: 
      - db-data:/data/db
    ports:
      - 27018:27018
    networks:
      - web

  app:
    build: .
    command: python app.py
    env_file:
      - ./docker/config/app.env
    volumes:
      - ./src:/src
    ports:
      - 9001:9001
    depends_on:
      - database
    networks:
      - web
    restart: on-failure

networks:
  web:
    driver: bridge
  
volumes:
  db-data: